version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=courseworkDB
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    image: adoptopenjdk:11-jre-hotspot
    volumes:
      - ./app/springsecuritydemo-0.0.1.jar:/app.jar
    command: java -jar app.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/courseworkDB
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8082:8082'
    depends_on:
      postgres:
        condition: service_healthy